############################
#  File : app_map_user.conf
#  Name : Imran Lateef
############################

# API num_messages time_in_seconds
[SCENARIO_START]
1
MAP_MT_FORWARD_SHORT_MESSAGE_REQUEST 10 10	
[/SCENARIO]
